# Generated by Django 5.0.2 on 2024-03-14 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_letter_created_at'),
        ('mailing', '0004_mailing_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='letter_header',
        ),
        migrations.AddField(
            model_name='mailing',
            name='letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='letters.letter', verbose_name='Письмо'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='sending_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время рассылки'),
        ),
    ]
