# Generated by Django 5.0.2 on 2024-03-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logstatus", "0007_remove_logmessage_client_info_logmessage_id_mailing_and_more"),
        ("mailing", "0006_mailing_created_at_mailing_sending_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="sending_status",
            field=models.ManyToManyField(to="logstatus.logmessage", verbose_name="Статус"),
        ),
    ]
