# Generated by Django 5.0.2 on 2024-03-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_logstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='sending_status',
        ),
        migrations.DeleteModel(
            name='LogStatus',
        ),
    ]
