# Generated by Django 5.0.2 on 2024-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0019_alter_mailing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='next_sending_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время следующей рассылки'),
        ),
    ]
