# Generated by Django 5.0.2 on 2024-03-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmessage',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='logmessage',
            name='letter_header',
        ),
        migrations.RemoveField(
            model_name='logmessage',
            name='sending_status',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='mailingsettings',
            name='period',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Mailing',
        ),
        migrations.DeleteModel(
            name='MailingSettings',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
