# Generated by Django 5.0.2 on 2024-03-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Имэйл клиента')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО клиента')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Аватар')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
    ]
