# Generated by Django 5.0.2 on 2024-03-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Letter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("letter_header", models.CharField(max_length=200, verbose_name="Тема письма")),
                ("letter_body", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "письмо",
                "verbose_name_plural": "письма",
            },
        ),
    ]
