# Generated by Django 5.0.2 on 2024-03-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logstatus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logmessage",
            name="sending_status",
            field=models.TextField(verbose_name="Статус"),
        ),
        migrations.RemoveField(
            model_name="logmessage",
            name="client_email",
        ),
        migrations.RemoveField(
            model_name="logmessage",
            name="letter_header",
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
