# Generated by Django 5.0.2 on 2024-03-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logstatus', '0003_logmessage_mailing_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmessage',
            name='mailing_name',
        ),
    ]
