# Generated by Django 5.0.2 on 2024-03-16 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logstatus', '0007_remove_logmessage_client_info_logmessage_id_mailing_and_more'),
        ('mailing', '0009_remove_mailing_sending_status_delete_logstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='id_mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='mailing.mailing', verbose_name='Айди_рассылки'),
        ),
    ]
